Resolves CoarchyP-100078: Statements improvement
coarchy/coarchy pull request #35
Opened 2023-12-31 13:06 UTC by marwand

Changes:

- Added Filter by process story/actor in activities dialog
- Added unconnect all activities button in activities dialog, 
- Show message & open activities dialog when trying to delete statement with connected activities
- Fix statments report link

2024-01-01 20:44 UTC, acetousk requested changes
Overall this looks good thanks!

2024-01-01 20:44 UTC, acetousk commented on screen/coarchy/cointernal/ValueStatements.xml
> +                                                <text-line/>
This should be a drop-down of actors using dynamic-options to filter by process story selected like https://github.com/coarchy/coarchy/blob/894f9ba7770a4d2989ce92744a2284ba8e52808c/screen/coarchy/cointernal/Process/EditProcessStory.xml#L230. If a process story isn't selected, then it should allow searching all of them.

2024-01-02 20:27 UTC, acetousk commented
In the ValueStatement screen's activities dialog, change connect to Add and disconnect to Remove. This will make it less cumbersome

2024-01-07 13:14 UTC, marwand commented
> In the ValueStatement screen's activities dialog, change connect to Add and disconnect to Remove. This will make it less cumbersome

Do you also want to change the form list header title "Connected Activities" to "Added Activities"?
Otherwise, I believe your comments have been resolved, let me know!

2024-01-10 16:06 UTC, merged